### ISSUE TITLE
Android: When renaming an account > Go button in keyboard does not submit the field/close the keyboard

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#498] opened 2019-03-29 23:54 UTC
![Wire 2019-03-29 at 23.00.01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46df9d8826c2d1f9deb0f213f710a2cd694733337b57ed7b20cbb379fd0e39111d0014f9121c4d4eeefcda29f0b139718f5c0befd26f0d74c76944abba831fed01a83c990dd4e8e8d51199a26867f5819d4e3914041d8cfc5435a39e4bce5ff24af300.png)

**Comment by davidyuk** [comment] 2019-04-01 07:01
duplicate of #478

**Closed by davidyuk** 2019-04-01 07:01 UTC
Labels: bug, duplicate
