### ISSUE TITLE
base.aepps.com broken on iphone < 8

### ISSUE THREAD

**Issue by kenodressel** [aeternity/aepp-base#451] opened 2019-03-13 09:08 UTC
I ran some tests with older iPhones. iPhone 6 + 7 had some issues while 8+ was fine.
## Configurations:
**iPhone 6s Plus, iOS 9.3, Safari 9.0:**
Base Aepp is not loading. Error:
![base aepps com_iphone6splus_ios9 3_safari9 0](https://user-images.githubusercontent.com/765921/54266547-e19b8000-4577-11e9-9ef0-7911f1d31a8a.png)

**iPhone 7, iOS 10.2, Safari 10.0:**
Base Aepp is loading but a password can not be set. The click on continue produces the following error:
![baseaeppdrone_iphone7_ios10 2_safari10 0](https://user-images.githubusercontent.com/765921/54266533-db0d0880-4577-11e9-8dfd-63ccebc6d745.png)

**Comment by j28** [comment] 2019-04-02 20:47
i was not able to reproduce either of these issues in the iOS simulator with an iPhone 6s Plus and iOS 12.1. i would say this is not a priority for the moment. we will revisit in the future. thanks for flagging!

**Comment by davidyuk** [comment] 2019-04-02 21:50
I have reproduced these issues on iOS 9.3 Simulator. In #511 I have fixed transpilation issues, but I can't find compatible polyfill for WebCrypto API that is used for secrets encoding.

**Comment by j28** [comment] 2019-04-09 18:31
"I can't find compatible polyfill for WebCrypto API that is used for secrets encoding." @davidyuk you are referring to the 2nd part of the issue? Should we create a separate issue for that and close this one (after somebody reviews the fix for the 1st part)?

**Comment by j28** [comment] 2019-04-11 15:00
@davidyuk will create a new issue for the remaining work and close this one.

**Closed** 2019-04-15 08:03 UTC
Labels: bug, priority, review
