### ISSUE TITLE
bottom part of base aepp is overlayed by iphone browser components

### ISSUE THREAD

**Issue by boyhulsteijn** [aeternity/aepp-base#415] opened 2019-02-26 13:26 UTC
When testing base aepp & drone aepp on an iphone, the bottom part of the screen was overlayed by iphone components. Making some some action buttons disappear.

**Comment by boyhulsteijn** [comment] 2019-02-26 13:28
![IMG_2704.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c4ede2b8851ca0012f5f900/125516c66e82c728ace21e0d46c1b9bd1cd0d4f9dbabf301b44fff9e2c4533317346f6282283b47dee172b515d5c4cfe41590b11fbfb882bf4b62e6c981e5ab38532022d8c6853beb2901eb70bbb258e4e84bebb8c4bc2e93f22f5c6.PNG)

**Comment by j28** [comment] 2019-05-06 12:22
Test @j28

**Comment by j28** [comment] 2019-05-06 21:08
i cannot get this to load inside the base aepp in my ios simulator or inside safari when i am debugging inside a desktop browser... and all of my other devices have bigger screens (so i can't reproduce it there either). is it possible that this is because the https gets changed to http? see attached.

![Screen Shot 2019-05-06 at 11.07.55 PM.png](https://images.zenhubusercontent.com/5c9e28c465f0aa09f9cdaf0c/abd2eefd-6ac7-48f3-adb9-d80ccb62826c)

**Comment by j28** [comment] 2019-05-07 09:28
retest after #713 us merged

**Comment by CedrikNikita** [comment] 2019-08-29 07:43
We wasn't able to reproduce this issue, but feel free to re-open a closed issue if needed.

**Closed by CedrikNikita** 2019-08-29 07:43 UTC
Labels: bug, can't reproduce
