### ISSUE TITLE
Issue in stage-identity amount to transfer not working

### ISSUE THREAD

**Issue by sadiqevani** [aeternity/aepp-base#290] opened 2019-01-08 13:54 UTC
Description:

When I'm trying to send AE from: https://stage-identity.aepps.com in the amount field, even though I input a number, it says: `This field must be -1.7e-14 or less`

How to replicate:

1. Go to https://stage-identity.aepps.com
2. Use phone to connect to your account
3. Select account that you want to send AE
4. Input amount of AE token you want to transfer.

**Comment by davidyuk** [comment] 2019-01-09 09:52
What balance is displayed in the desktop version? Have you selected a proper network? Looks like it assumes that you don't have tokens.

Actually, transaction signing by the mobile version is broken until #293 gets merged.

**Comment by j28** [comment] 2019-04-10 17:05
@sadiqevani @davidyuk if either of you is able to reproduce this currently could you provide a screenshot?

**Comment by sadiqevani** [comment] 2019-04-11 10:57
@j28 unreproducible issues means its fixed.

**Comment by j28** [comment] 2019-04-11 14:34
Thank you @sadiqevani 

I will close it for now. If anyone experiences this issue again we can reopen (or make a new one).

**Closed by j28** 2019-04-11 14:34 UTC
Labels: bug, p1: clarify
